### ISSUE TITLE
Will the Tuxedo Update receive update notifications?

### ISSUE THREAD

**Issue by nick6352683** [andtrev/Tuxedo-Software-Updater#1]
Here is a crazy question. Will this plugin receive update notifications, so I don't have to visit this site every week or so to see if I have the latest version? It would be rather ironic if THIS kind of software would not receive any automated updates... I looked at the plugin's main file's header, and I don't think it is configured to receive updates, at least from a site driven by the Tuxedo Software Updater. I am not aware if github has an updating feature, or how it's even configured if it has the ability to update the code...

In the meantime..., this plugin is crazy amazing!!!

**Comment by andtrev** [comment]
At this moment it doesn't automatically update itself. I'll add that into the next version, when I can get a proper release site up and running. For now there's just this github repo :)

**Comment by nick6352683** [comment]
Thanks for the info. I was just wondering... 

Nick DerAvedissian
QuickerThemes.com - Quicker, Easier, Better !
Phone: (818) 634-1055 

    On Wednesday, October 4, 2017, 6:36:01 PM PDT, Trevor Anderson <notifications@github.com> wrote:  
 
 
At this moment it doesn't automatically update itself. I'll add that into the next version, when I can get a proper release site up and running. For now there's just this github repo :)
